[package]
name = "osiris-audit"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
thiserror = { workspace = true }
osiris-schema = { path = "../osiris-schema" }

[dev-dependencies]
tempfile = { workspace = true }
