[package]
name = "osiris-storage-sqlite"
version.workspace = true
edition.workspace = true

[dependencies]
serde_json = { workspace = true }
uuid = { workspace = true }
rusqlite = { workspace = true }
tracing = { workspace = true }
osiris-schema = { path = "../osiris-schema" }
osiris-storage = { path = "../osiris-storage" }
osiris-query = { path = "../osiris-query" }

[dev-dependencies]
tempfile = { workspace = true }
