[package]
name = "osiris-k8s-context"
version.workspace = true
edition.workspace = true

[dependencies]
reqwest = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
osiris-schema = { path = "../osiris-schema" }
osiris-pipeline = { path = "../osiris-pipeline" }

[dev-dependencies]
axum = { workspace = true }
tempfile = { workspace = true }
