[package]
name = "osiris-agent"
version.workspace = true
edition.workspace = true

[[bin]]
name = "osirisd"
path = "src/main.rs"

[dependencies]
serde = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
hostname = { workspace = true }
tracing = { workspace = true }
osiris-schema = { path = "../osiris-schema" }
osiris-config = { path = "../osiris-config" }
osiris-health = { path = "../osiris-health" }
osiris-selftelemetry = { path = "../osiris-selftelemetry" }
osiris-sensor-api = { path = "../osiris-sensor-api" }
osiris-pipeline = { path = "../osiris-pipeline" }
osiris-bus = { path = "../osiris-bus" }
osiris-sensors-process = { path = "../osiris-sensors/process" }
osiris-sensors-fs = { path = "../osiris-sensors/fs" }
osiris-sensors-net = { path = "../osiris-sensors/net" }
osiris-sensors-identity = { path = "../osiris-sensors/identity" }
osiris-sensors-systemd = { path = "../osiris-sensors/systemd" }
osiris-sensors-persistence = { path = "../osiris-sensors/persistence" }
osiris-sensors-container = { path = "../osiris-sensors/container" }
osiris-generator = { path = "../../generator" }

[dev-dependencies]
tempfile = { workspace = true }
serde_json = { workspace = true }
