[package]
name = "osiris-bus"
version.workspace = true
edition.workspace = true

[dependencies]
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
osiris-schema = { path = "../osiris-schema" }
osiris-pipeline = { path = "../osiris-pipeline" }
osiris-selftelemetry = { path = "../osiris-selftelemetry" }

[dev-dependencies]
tempfile = { workspace = true }
uuid = { workspace = true }
