[package]
name = "osiris-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "osiris"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
rpassword = { workspace = true }
osiris-schema = { path = "../osiris-schema" }
osiris-transport = { path = "../osiris-transport" }
osiris-command = { path = "../osiris-command" }
uuid = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
rustls = { workspace = true }
