[package]
name = "osiris-server"
version.workspace = true
edition.workspace = true

[[bin]]
name = "osiris-server"
path = "src/main.rs"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
axum = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
osiris-schema = { path = "../osiris-schema" }
osiris-storage = { path = "../osiris-storage" }
osiris-storage-sqlite = { path = "../osiris-storage-sqlite" }
osiris-api = { path = "../osiris-api" }
osiris-selftelemetry = { path = "../osiris-selftelemetry" }
osiris-fileutil = { path = "../osiris-fileutil" }
osiris-detect = { path = "../osiris-detect" }
osiris-correlate = { path = "../osiris-correlate" }
osiris-baseline = { path = "../osiris-baseline" }
osiris-risk = { path = "../osiris-risk" }
osiris-evidence = { path = "../osiris-evidence" }
osiris-audit = { path = "../osiris-audit" }
uuid = { workspace = true }
tower-http = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
uuid = { workspace = true }
tower = { workspace = true }
