[package]
name = "osiris-transport"
version.workspace = true
edition.workspace = true

[dependencies]
osiris-schema = { path = "../osiris-schema" }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
async-trait = { workspace = true }
rustls = { workspace = true }
tokio-rustls = { workspace = true }
rustls-pemfile = { workspace = true }
rcgen = { workspace = true }
x509-parser = { workspace = true }
zstd = { workspace = true }
time = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
